### PR TITLE
fix: change to use config singleton instead of $this on static method

### PR DESCRIPTION
**Pull request by Neumes**

### CODE REVIEW

**Comment by camfindlay** [comment]
Thanks @Neumes was this causing a bug specifically? Seeing as the builds are failing might need to work out what's going on there too! I'll look into that if you can come up with a small test for this - deal? 😄

**Comment by Neumes** [comment]
This one gets hit when yaml config is used instead of _ss_environment globals. More specific to the environments we use for testing and production systems where it's nicer for us to use yaml config.

**Comment by camfindlay** [comment]
Ah I see, ok. So you've check that this change will work for both yaml config and environment based config? If yes I'll merge in :+1:

**Comment by camfindlay** [comment]
Added to #21

**Pull request closed without merging**
